### PR TITLE
Make more robust to potential network failures

### PR DESCRIPTION
**Pull request by merivale**
Forgive my OCD, but I made a few unrelated edits in pursuit of consistency. And updated the dependencies while I was at it.

The significant commit is the penultimate one (1e35c41). And I figure the last commit (75d14e3) can't hurt either.

It remains to be seen whether this will fix the problem you've been noticing, which I haven't been able to recreate. What I have done is tested this against a local instance of the train app - and the sync script survives me killing the whole docker container (while logging ECONNREFUSED errors each second), which I take to be a good sign. Without this patch, killing the docker container makes the sync script crash.

### CODE REVIEW

**Review by hcarver — APPROVED** [review]
This all looks good to me. Just to check, when the docker container came back up, did the sync immediately become active?

One other thing to check: kill the train container, change a file, the restart train. And hopefully the updated file would get uploaded to train, as if it had never been down. That would be *amazing*.

**Comment by merivale** [comment]
Yes, on both counts. It keeps watching for changes (and trying more uploads) even if requests fail, and files are only removed from the `changed_files` array when the request succeeds.

**Comment by hcarver** [comment]
Excellent. When this is merged, ~let's bump the minor version number, then~ I can publish it. When it's live please could you update all our JS-based repos to use it?

**Comment by hcarver** [comment]
Thanks. Published now, as 1.6.0 @merivale

**Pull request merged**
